version: '3.9'

services:

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /app-frontend
    volumes:
      - ./frontend/src:/app-frontend/src
    depends_on:
      - backend
    tty: true
    stdin_open: true
  
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3001:3001
    working_dir: /app-backend
    command: dev
    volumes:
      - ./backend/src:/app-backend/src
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    tty: true
    stdin_open: true

  db:
    container_name: db
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
  
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 30s

